networks:
  pipeline_net:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    container_name: taxi_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_taxi_data:/var/lib/postgresql/data
    networks:
      - pipeline_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: taxi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pipeline_net

volumes:
  postgres_taxi_data: